language: python

python:
  - 3.6

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash ./miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pytest;
      source activate testenv;
      conda install --file requirements.txt;

install:
    - python setup.py install

script: py.test
